# ingress


apiVersion : v1-ingress
kind  : ingress
metadata :
  name : my-app-ingress
# path based  routing
specs :
  rules :
    - host: my-app.local
      http :
        paths :
          - path : /
            pathType : prefix
            backend :
              service :
                name : my-app-service
                port :
                  number : 80